SIGS/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  # Categories
  get 'categories/new' => 'categories#new' , as: 'categories_new'
  post 'categories/create' => 'categories#create' , as: 'categories_create'
  get 'categories/index' => 'categories#index' , as: 'categories_index'
  get 'categories/edit/:id' => 'categories#edit', as: 'categories_edit'
  patch 'categories/update/:id', controller: 'categories', action: 'update', as: 'categories_update'
  get 'categories/destroy/:id', controller: 'categories', action: 'destroy', as: 'categories_destroy'

  # Sessions
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  # User
  get 'users/index' => 'users#index', as: 'user_index'
  get 'users/new' => 'users#new' , as: 'user_new'
  post 'users/new' => 'users#create' , as:'user_create'
  get '/users/:id' => 'users#show', as: 'user'
  get 'users/edit/:id' => 'users#edit', as: 'user_edit'
  patch 'users/update/:id', controller: 'users', action: 'update', as: 'user_update'
  get 'users/destroy/:id', controller: 'users', action: 'destroy', as: 'user_destroy'

  # Coordinator

  # Department Assistant

  # Administrative Assistant
  get 'administrative_assistants/registration_request' => 'administrative_assistants#registration_request', as: 'registration_request'
  get 'administrative_assistants/enable_registration/:id' => 'administrative_assistants#enable_registration', as: 'enable_registration'
  get 'administrative_assistants/decline_registration/:id' => 'administrative_assistants#decline_registration', as: 'decline_registration'
  get 'administrative_assistants/destroy_users/:id' => 'administrative_assistants#destroy_users', as: 'destroy_users'

  # Room
  get 'rooms/index' => 'rooms#index', as: 'room_index'
  post 'rooms/index' => 'rooms#index', as: 'room_index_post'
  get 'rooms/edit/:id' => 'rooms#edit', as: 'room_edit'
  patch 'rooms/update/:id' => 'rooms#update'
  get 'rooms/show/:id' => 'rooms#show', as: 'room'
  get 'room/destroy/:id', controller: 'rooms', action: 'destroy', as: 'destroy_room'
  get 'rooms/json_of_categories_by_school_room' => 'rooms#json_of_categories_by_school_room'
  post 'rooms/filter_rooms' => 'rooms#filter_rooms', as: 'rooms_filter'

  # Course
  get 'courses/courses_by_user' => 'courses#courses_by_user', as: 'courses_by_user'

  #SchoolRooms
  get 'school_rooms/index' => 'school_rooms#index', as: 'school_rooms_index'
  get 'school_rooms/new' => 'school_rooms#new', as: 'school_rooms_new'
  post 'school_rooms/create' => 'school_rooms#create'
  get 'school_rooms/edit/:id' => 'school_rooms#edit', as: 'school_rooms_edit'
  patch 'school_rooms/update/:id', controller: 'school_rooms', action: 'update', as: 'school_rooms_update'
  post 'school_rooms/search_disciplines' => 'school_rooms#search_disciplines', as: 'search_disciplines'
  get 'school_rooms/destroy/:id', controller: 'school_rooms', action: 'destroy', as: 'destroy_school_room'
  get 'school_rooms/search_courses/:code' => 'school_rooms#search_courses', as: 'search_courses'

  # Parsers
  post "/upload_buildings", controller: 'parsers', action: 'upload_buildings'
  post "/upload", controller: 'parsers', action: 'upload_rooms'
  get "/parsers", controller: 'parsers', action: 'index', as: "index_parser"
  post "/upload_department", controller: 'parsers', action: 'upload_departments'
  post "/upload_courses", controller: 'parsers', action: 'upload_courses'
  post "/upload_disciplines", controller: 'parsers', action: 'upload_disciplines'
  #resources :parsers

  # Period
  get 'periods/index' => 'periods#index' , as: 'period_index'
  get 'periods/edit/:id' => 'periods#edit', as: 'period_edit'
  post 'periods/update' => 'periods#update', as: 'period_update'

  # Reports
  get 'reports/by_room'=> 'reports#by_room', as: 'reports_by_room'
  get 'reports/generate_by_room' => 'reports#generate_by_room', as: 'generate_by_room'
  get 'reports/json_of_rooms_by_department' => 'reports#json_of_rooms_by_department'
  get 'reports/json_of_rooms_with_parts_of_name' => 'reports#json_of_rooms_with_parts_of_name'
  post 'reports/generate_by_room' => 'reports#generate_by_room'

  # Reports School Rooms
  get 'reports_school_rooms/school_room_all' => 'reports_school_rooms#report_school_room_all', as: 'reports_school_room_all'
  get 'reports_school_rooms/school_rooms_allocated' => 'reports_school_rooms#report_school_room_allocated', as: 'reports_school_room_allocated'
  get 'reports_school_rooms/school_room_not_allocated' => 'reports_school_rooms#report_school_room_not_allocated', as: 'reports_school_room_not_allocated'
  get 'reports_school_rooms/school_room' => 'reports_school_rooms#school_reports', as: 'reports_school_room'

  #Reports by building
  get 'reports/by_building'=> 'reports#by_building', as: 'reports_by_building'
  get 'reports/generate_by_building/:id' => 'reports#generate_by_building', as: 'generate_by_building'
  post 'reports/by_building' => 'reports#by_building', as: 'reports_by_building_post'

  #Reports Disciplines
  get 'reports_disciplines/generate_by_discipline/:id' => 'reports_disciplines#generate_by_discipline', as: 'generate_by_discipline'
  get 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline'
  post 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline_post'

  # Allocation
  get 'allocations/new/:school_room_id' => 'allocations#new' , as: 'allocations_new'
  post 'allocations/create' => 'allocations#create' , as: 'allocations_create'
  post 'allocations/allocation_by_solicitation' => 'allocations#allocation_by_solicitation' , as: 'allocation_by_solicitation'
  get 'allocations/destroy/:id', controller: 'allocations', action: 'destroy', as: 'allocations_destroy'
  get 'allocations/room_allocations_by_day' => 'allocations#room_allocations_by_day', as: 'room_allocations_by_day'
  get 'allocations/destroy_all_allocation_date/:id', controller: 'allocations', action: 'destroy_all_allocation_date', as: 'allocations_destroy_all_allocation_date'
  get 'allocations/destroy_all_allocations/:id' => 'allocations#destroy_all_allocations', as: 'allocations_destroy_all_allocations'

  # allocation_extension
  get 'allocation_extensions/new' => 'allocation_extensions#new' , as: 'allocation_extensions_new'
  post 'allocation_extensions/create' => 'allocation_extensions#create' , as: 'allocation_extensions_create'

  # Extension
  post 'extensions/create' => 'extensions#create' , as: 'extensions_create'

  # Solicitation
  get 'solicitations/index' => 'solicitations#index', :as => 'solicitations_index'
  get 'solicitations/show/' => 'solicitations#show', as: 'solicitations_show'
  get 'solicitations/allocation_period/:school_room_id' => 'solicitations#allocation_period', :as => 'allocation_period'
  get 'solicitations/adjustment_period/:school_room_id' => 'solicitations#adjustment_period', :as => 'adjustment_period'
  post 'solicitations/save_allocation_period' => 'solicitations#save_allocation_period', :as => 'save_allocation_period'
  post 'solicitations/save_adjustment_period' => 'solicitations#save_adjustment_period', :as => 'save_adjustment_period'
  get 'solicitations/avaliable_rooms_by_department' => 'solicitations#avaliable_rooms_by_department', :as => 'avaliable_rooms_by_department'
  get 'solicitations/recuse_solicitation' => 'solicitations#recuse_solicitation', as: 'solicitations_recuse_solicitation'
  post 'solicitations/approve_solicitation' => 'solicitations#approve_solicitation', as: 'solicitations_approve_solicitation'

  # API Users
  get 'api_users/index' => 'api_users#index', as: 'api_users_index'
  get 'api_users/new' => 'api_users#new', as: 'api_users_new'
  post 'api_users/create' => 'api_users#create', as: 'api_users_create'
  get 'api_users/edit/:id' => 'api_users#edit', as: 'api_users_edit'
  put 'api_users/update/:id' => 'api_users#update', as: 'api_users_update'
  get 'api_users/show/:id' => 'api_users#show', as: 'api_users_show'
  get 'api_users/destroy/:id' => 'api_users#destroy', as: 'api_users_destroy'

  # API
  namespace :api, default: { format: :json }, path: '/api' do
    get 'all_rooms' => 'apis#all_rooms'
    get 'building/:code' => 'apis#buildings'
    get 'school_rooms/all' => 'apis#all_school_room'
    get 'department_allocations/:code' => 'apis#department_allocations'
    get 'discipline_allocations/:code' => 'apis#discipline_allocations'
    get 'school_rooms/all_school_rooms' => 'apis#all_school_rooms', as: 'api_all_school_rooms'
    get 'school_rooms_of_room/:code' => 'apis#school_rooms_of_room'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

SIGS/app/models/room.rb
# frozen_string_literal: true

# Classe modelo da Sala
class Room < ApplicationRecord
  belongs_to :building
  has_many :allocations, dependent: :destroy
  belongs_to :department
  has_and_belongs_to_many :category
  belongs_to :department

  # Codigo da sala
  validates :code,
            presence: { message: 'Informe o código da sala' },
            uniqueness: { message: 'Uma sala com esse código já foi cadastra' }

  # Nome da sala
  CHARACTERS_MINIMUM_FOR_THE_NAME_EXCEPTION = 'O Nome deve ter no mínimo 2
   caracteres'.freeze
  CHARACTERS_MAXIMUM_FOR_THE_NAME_EXCEPTION = 'Nome deve ter no máximo 50
   caracters'.freeze

  validates_length_of :name,
                      within: 2..50,
                      too_short: CHARACTERS_MINIMUM_FOR_THE_NAME_EXCEPTION,
                      too_long: CHARACTERS_MAXIMUM_FOR_THE_NAME_EXCEPTION

  # Capacidade da sala
  MINIMUM_FOR_THE_CAPACITY_EXCEPTION = 'A capacidade mínima é 5 vagas'.freeze
  MAXIMUM_FOR_THE_CAPACITY_EXCEPTION = 'A capacidade máxima é 500 vagas'.freeze

  validates_numericality_of :capacity,
                            greater_than_or_equal_to: 5,
                            message: MINIMUM_FOR_THE_CAPACITY_EXCEPTION

  validates_numericality_of :capacity,
                            less_than_or_equal_to: 500,
                            message: MAXIMUM_FOR_THE_CAPACITY_EXCEPTION
end

SIGS/app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Classe responsavel pelos metodos controladores de sala
class RoomsController < ApplicationController
  before_action :logged_in?
  before_action :authenticate_not_deg?, except: [:index, :show]

  def index
    @rooms = Room.all
    @buildings = Building.all
    filter_by_name
    filter_by_code
    filter_by_capacity
    filter_by_buildings
    filter_by_wings
  end

  def filter_by_capacity
    return unless params[:capacity].present?
    @rooms = @rooms.where('capacity >= ?', params[:capacity])
  end

  def filter_by_buildings
    return unless params[:building_id].present?
    @rooms = @rooms.where(building_id: params[:building_id])
  end

  def filter_by_wings
    return unless params[:wing].present?
    @rooms = @rooms.joins(:building).where(buildings: { wing: params[:wing] })
  end

  def filter_by_name
    return unless params[:name].present?
    @rooms = @rooms.where('rooms.name LIKE ?', "%#{params[:name]}%")
  end

  def filter_by_code
    return unless params[:code].present?
    @rooms = @rooms.where('rooms.code' => params[:code])
  end

  def edit
    find_rooms
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      success_mesage = 'Dados da sala atualizados com sucesso'
      redirect_to room_index_path(@room.id), flash: { success: success_mesage }
    else
      flash[:error] = 'Dados não foram atualizados'
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @coordinator = Coordinator.find_by(user_id: current_user.id)
    if (permission[:level] == 2 && @room.department.name == 'PRC') ||
       (permission[:level] == 1 && @coordinator.course.department == @room.department)
      @room.destroy
      flash[:success] = 'Sala excluida com sucesso'
    else
      flash[:error] = 'Não possui permissão para excluir sala'
    end
    redirect_to room_index_path
  end

  def show
    find_rooms
  end

  def json_of_categories_by_school_room
    school_room_id = params[:school_room_id]
    result = []
    allocations = Allocation.where(school_room_id: school_room_id)
    allocations.each do |allocation|
      result.push [
        allocation.start_time,
        allocation.final_time,
        allocation.day,
        allocation.room.name
      ]
    end
    render inline: result.to_json
  end

  private

  def find_rooms
    @room = Room.find(params[:id])
    @room_categories = @room.category
    find_allocation(@room)
  end

  def find_allocation(room)
    room_id = room.id
    @allocations = Allocation.where(room_id: room_id)
    @allocations_extensions = AllocationExtension.where(room_id: room_id)
  end

  def room_params
    params[:room].permit(
      :id,
      :code,
      :name,
      :capacity,
      :active,
      :time_grid_id,
      :building_id,
      category_ids: []
    )
  end
end

SIGS/app/views/rooms/edit.html.erb
<h1>Editar Sala</h1>

  <ul id="erro-message">
    <% @room.errors.messages.values.each do |msg| %>
      <% msg.each do |m| %>
        <li><%= m %></li>
      <%end %>
    <% end %>
  </ul>

  <%= form_for @room,:url => {:action=> 'update'} do |room| %>
    <%= room.label :code, 'Código da Sala' %>
    <%= room.text_field :code, class: 'form-control', value: @room.code %><br>

    <%= room.label :name, 'Nome' %>
    <%= room.text_field :name, class: 'form-control', value: @room.name %><br>

    <%= room.label :capacity, 'Capacidade' %>
    <%= room.text_field :capacity, class: 'form-control', value: @room.capacity %><br>

    <%= room.hidden_field :actual_capacity, value: @room.capacity %>

    <%= room.label :active, 'Ativo' %>
    <%= room.check_box :active, class: 'form-control',style: 'text-align:left; width: auto' %><br>

    <p> <b> Categorias </b> </p>
    <div class="checkbox-group">
      <%= room.collection_check_boxes(:category_ids,all_categories,:id,:name, include_blank: true) do |box| %>
        <%= box.check_box %>  <%= box.text %> <br>
      <% end %>
    </div>

    <div class='actions'>
      <%= room.submit 'Salvar', class: 'pull-right btn btn-default btn-success' %>
    </div>
    </div>
  <% end %>

SIGS/app/views/rooms/index.html.erb
<h1>Salas</h1>
<table class="table">
  <tr>
  <%= form_tag(room_index_post_path, :method => :post) do %>
    <td>
      <%= label_tag("Nome") %>
      <%= text_field_tag 'name', nil, placeholder: 'Digite o nome da sala...', size: '40', class: 'form-control' %>
    </td>
    <td>
      <%= label_tag("Código") %>
      <%= text_field_tag 'code', nil, placeholder: 'Digite o código da sala...', size: '25', class: 'form-control' %>
    </td>
    <td>
      <%= label_tag("Capacidade") %>
      <%= number_field_tag 'capacity', nil, placeholder: 'Insira a quantidade...', size: '500', class: 'form-control' %>
    </td>
  </tr>

  <tr>
    <td>
      <%= label_tag("Ala") %>
      <% itens = [["NORTE"], ["CENTRAL"], ["SUL"]] %>
      <%= select_tag 'wing', options_for_select(itens, " "), include_blank: true %>
    </td>
    <td>
      <%= label_tag("Prédio") %>
      <%= select_tag 'building_id', options_for_select(@buildings.map{ |building| [building.name, building.id, { 'data-wing' => building.wing }] }), include_blank: true %>
    </td>
  </tr>

  <tr>
    <td>
      <br>
      <%= submit_tag "Pesquisar", class: "btn btn-success" %>
    </td>
    <td colspan="2">
      <br>
      <%= link_to "Limpar Filtros", room_index_path, class: "btn btn-primary pull-right" %>
    </td>
  </tr>

<% end %>

</table>

  <p>
    <b>Funcionamento:&nbsp;</b>
    <%= label_tag(:id_all , "Todas") %>
    <%= radio_button_tag(:room_status_filter, "all", true, :id => "id_all") %>
    <%= label_tag(:id_active, "Ativa") %>
    <%= radio_button_tag(:room_status_filter, "active", false, :id => "id_active") %>
    <%= label_tag(:id_anactive, "Inativa") %>
    <%= radio_button_tag(:room_status_filter, "inactive", false, :id => "id_anactive") %>
  </p>

  <% if @rooms.count == 0 %>
    <h3>Nenhuma sala encontrada.</h3>
  <% else %>
    <table class="table">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Ativo</th>
        <th>Prédio</th>
        <% if permission[:level] != 0 %>
          <th style="text-align:center">Alterar</th>
        <% end %>
        <th style="text-align:center">Visualizar</th>
      </tr>
    </thead>
    <tbody class="show_room">
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.code %></td>
          <td><%= room.name %></td>
          <td id="active_room"><%=  ((room.active) ? 'Sim' : 'Não')  %></td>
          <td><%= room.building.name %></td>
          <% if permission[:level] != 0 %>
            <td style="text-align:center"><%= link_to image_tag("icon_edit.png"), room_edit_path(room.id) %></td>
          <% end %>  
          <td style="text-align:center"><%= link_to image_tag("icon_view.png"), room_path(room.id) %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% end %>

<script>
  $("input:radio").on('click', function() {
    $(".show_room").empty();
    var roomStatus = $(this).attr("value");

    if (roomStatus === "active") {
      <% @rooms.each do |room| %>
        if (<%= room.active %>) {
          $(".show_room").append(
            "<tr>"
              + "<td><%=room.code%></td>"
              + "<td><%= room.name %></td>"
              + "<td id='active_room'><%=((room.active) ? 'Sim' : 'Não')  %></td>"
              + "<td><%= room.building.name %></td>"
              + '<td style="text-align:center"><%= link_to image_tag("icon_edit.png"), room_edit_path(room.id) %></td>'
              + '<td style="text-align:center"><%= link_to image_tag("icon_view.png"), room_path(room.id) %></td>'
            + "</tr>"
          );
        }
      <%end%>
    } else if (roomStatus === "inactive") {
       <% @rooms.each do |room| %>
         if (!<%= room.active %>) {
            $(".show_room").append(
              "<tr>"
                + "<td><%=room.code%></td>"
                + "<td><%= room.name %></td>"
                + "<td id='active_room'><%=((room.active) ? 'Sim' : 'Não')  %></td>"
                + "<td><%= room.building.name %></td>"
                + '<td style="text-align:center"><%= link_to image_tag("icon_edit.png"), room_edit_path(room.id) %></td>'
                + '<td style="text-align:center"><%= link_to image_tag("icon_view.png"), room_path(room.id) %></td>'
              + "</tr>"
            );
          }
      <%end%>
    } else {
      // roomStatus === all
      <% @rooms.each do |room| %>
        $(".show_room").append(
          "<tr>"
            + "<td><%=room.code%></td>"
            + "<td><%= room.name %></td>"
            + "<td id='active_room'><%=((room.active) ? 'Sim' : 'Não')  %></td>"
            + "<td><%= room.building.name %></td>"
            + '<td style="text-align:center"><%= link_to image_tag("icon_edit.png"), room_edit_path(room.id) %></td>'
            + '<td style="text-align:center"><%= link_to image_tag("icon_view.png"), room_path(room.id) %></td>'
          + "</tr>"
        );
      <%end%>
    }

  });

  $('select#wing').on('change', function() {
    var selected = $(this).val();
    $('select#building_id').find('option').removeClass('hide');
    $('select#building_id').find('option').not('option[data-wing="' + selected + '"]').addClass('hide');
  });
</script>

SIGS/app/views/rooms/show.html.erb
<h1>Sala: <%= @room.name %></h1>
<div class="row">
  <div class="col-md-6">
    <ul class="list-group">
      <li class="list-group-item">Código: <%= @room.code %></li>
      <li class="list-group-item">Capacidade: <%= @room.capacity %></li>
      <li class="list-group-item">Status: <%= ((@room.active) ? 'Ativo' : 'Inativo') %></li>
      <li class="list-group-item">Prédio: <%= @room.building.name %></li>
    </ul>
  </div>
  <div class="col-md-6">
    <ul class="list-group">
      <li class="list-group-item"><h4>Recursos:</h4></li>
      <% @room_categories.each do |room_category| %>
        <li class="list-group-item"><%= room_category.name %></li>
      <% end %>
    </ul>
  </div>
</div>

<table class="table tableViewAllocation table-bordered">
  <thead>
    <tr>
      <% days = %w(Segunda Terça Quarta Quinta Sexta Sábado) %>
      <th>Horários</th>
      <% days.each do |day| %>
        <th><%= day %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% (6..23).each do |hour| %>
      <tr>
        <th><%= (hour < 10 ? "0#{hour}" : hour) %>:00</th>
        <% days.each do |day| %>
          <td data-day-hour="<%= "#{day}#{hour}" %>"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="hide allocationsDiv">
  <% @allocations.each do |allocation|
    start_time = allocation.start_time.strftime('%H:%M').to_i
    rowspan = allocation.final_time.strftime('%H').to_i - start_time
  %>
    <p class="dataAllocation" data-day="<%= allocation.day %>" data-hour="<%= start_time %>" data-rowspan="<%= rowspan %>">
      <%= allocation.school_room.discipline.name %>
      <a href="#!" class="openModal" data-school-room="<%= allocation.school_room.id %>" data-courses="<% allocation.school_room.courses.each do |course| %><%= (course == allocation.school_room.courses.last ? course.name : "#{course.name}, ") %><% end %>" data-discipline="<%= allocation.school_room.discipline.name %>" data-vacancies="<%= allocation.school_room.vacancies %>" data-department="<%= allocation.school_room.discipline.department.name %>">
        <small>Turma: <%= allocation.school_room.name %></small>
      </a>
      <% unless allocation.school_room.category.empty? %>
        <ul class="list-group listResources" data-day-hour="<%= "#{allocation.day}#{start_time}" %>">
          <li class="list-group-item"><h4>Recursos:</h4></li>
          <% allocation.school_room.category.each do |cat| %>
            <li class="list-group-item"><%= cat.name %></li>
          <% end %>
        </ul>
      <% end %>
    </p>
  <% end %>
</div>

  <!-- <% @allocations_extensions.each do |allocation_extension| %>
  <h2><%= allocation_extension.id %><br></h2>
  <h2><%= allocation_extension.periodicity %><br></h2>
  <h2><%= allocation_extension.start_time.strftime('%H:%M') %><br></h2>
  <h2><%= allocation_extension.final_time.strftime('%H:%M') %><br></h2>
  <h2><%= allocation_extension.inicial_date %><br></h2>
  <h2><%= allocation_extension.final_date %><br></h2>
  <% end %> -->

<!-- Modal School Room -->
<div class="modal fade" id="modalSchollRoom" tabindex="-1" role="dialog" aria-labelledby="modalTitle">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="schoolRoomTitle"></h4>
      </div>
      <div class="modal-body">
        <ul class="list-group listSchoolRoom">
          <li class="list-group-item" id="itemCourse"></li>
          <li class="list-group-item" id="itemDiscipline"></li>
          <li class="list-group-item" id="itemDepartment"></li>
          <li class="list-group-item" id="itemVacancies"></li>
        </ul>
        <table class="table table-striped tableModalSchoolRoom">
          <thead>
            <tr>
              <th>Horário</th>
              <th>Dia</th>
              <th>Sala</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $('.dataAllocation').each(function() {
      var dataAllocation = $(this);
      var day = dataAllocation.attr("data-day");
      var hour = dataAllocation.attr("data-hour");
      var rowspan = dataAllocation.attr("data-rowspan");
      var tdMatching = $('.tableViewAllocation td[data-day-hour="' + day + hour + '"]');

      if (tdMatching.is(':empty')) {
        dataAllocation.appendTo(tdMatching).find('a').appendTo(tdMatching);
        if (rowspan > 1 ) {
          tdMatching.attr("rowspan", rowspan);
          for (i = 1; i < rowspan; i++) {
            var finalHour = parseInt(hour) + i;
            $('.tableViewAllocation td[data-day-hour="' + day + finalHour + '"]').remove();
          }
        }
      } else {
        (tdMatching).append(' | ');
        dataAllocation.find('a').appendTo(tdMatching);
      }
    });

    $('.openModal').on('click', function() {
      var school_room_id = $(this).attr('data-school-room');
      var hourDay = $(this).parent().attr('data-day-hour');

      $('#schoolRoomTitle').text($(this).find('small').text());
      $('#itemCourse').text('Curso(s): ' + $(this).attr('data-courses'));
      $('#itemDepartment').text('Departamento: ' + $(this).attr('data-department'));
      $('#itemDiscipline').text('Disciplina: ' + $(this).attr('data-discipline'));
      $('#itemVacancies').text('vagas: ' + $(this).attr('data-vacancies'));
      $('#modalSchollRoom .listResources').appendTo('.allocationsDiv');
      $('.allocationsDiv .listResources[data-day-hour="' + hourDay + '"]').insertAfter('.listSchoolRoom');

      $.getJSON(
        '<%= request.base_url %>/rooms/json_of_categories_by_school_room?school_room_id=' + school_room_id,

        function(data) {
          $('.tableModalSchoolRoom tbody').empty();

          $(data).each(function(i, d) {
            var startTime = d[0].split('T');
            var startTime = startTime[1].split(':');
            var hourStart = startTime[0];
            var finalTime = d[1].split('T');
            var finalTime = finalTime[1].split(':');
            var hourFinal = finalTime[0];
            var tr = '<tr><td>' + hourStart + ':00 - ' + hourFinal + ':00</td><td>' + d[2] + '</td><td>' + d[3] + '</td></tr>';

            $(tr).appendTo('.tableModalSchoolRoom tbody');
          });
        }
      );

      $('#modalSchollRoom').modal('show');
    });

    $('.tableViewAllocation tbody td').on('mouseover', function() {
      var td = $(this);
      if (!td.is(':empty')) {
        var discipline = td.find('p').text();
        td.find('small').each(function() {
          var schoolRoom = $(this).text();
          $('.tableViewAllocation tbody td:contains("' + discipline + '")').find('a:contains("' + schoolRoom + '")').parent().addClass('tdHover');
        });
      }
    }).on('mouseleave', function() {
      $('.tableViewAllocation tbody td').removeClass('tdHover');
    });

    // function getRandomColor() {
    //   var nums = '0123456789ABCDEF';
    //   var color = '#';
    //   for (var i = 0; i < 6; i++ ) {
    //       color += nums[Math.floor(Math.random() * 16)];
    //   }
    //   return color;
    // }
  });
</script>