SIGS/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  # Categories
  get 'categories/new' => 'categories#new' , as: 'categories_new'
  post 'categories/create' => 'categories#create' , as: 'categories_create'
  get 'categories/index' => 'categories#index' , as: 'categories_index'
  get 'categories/edit/:id' => 'categories#edit', as: 'categories_edit'
  patch 'categories/update/:id', controller: 'categories', action: 'update', as: 'categories_update'
  get 'categories/destroy/:id', controller: 'categories', action: 'destroy', as: 'categories_destroy'

  # Sessions
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  # User
  get 'users/index' => 'users#index', as: 'user_index'
  get 'users/new' => 'users#new' , as: 'user_new'
  post 'users/new' => 'users#create' , as:'user_create'
  get '/users/:id' => 'users#show', as: 'user'
  get 'users/edit/:id' => 'users#edit', as: 'user_edit'
  patch 'users/update/:id', controller: 'users', action: 'update', as: 'user_update'
  get 'users/destroy/:id', controller: 'users', action: 'destroy', as: 'user_destroy'

  # Coordinator

  # Department Assistant

  # Administrative Assistant
  get 'administrative_assistants/registration_request' => 'administrative_assistants#registration_request', as: 'registration_request'
  get 'administrative_assistants/enable_registration/:id' => 'administrative_assistants#enable_registration', as: 'enable_registration'
  get 'administrative_assistants/decline_registration/:id' => 'administrative_assistants#decline_registration', as: 'decline_registration'
  get 'administrative_assistants/destroy_users/:id' => 'administrative_assistants#destroy_users', as: 'destroy_users'

  # Room
  get 'rooms/index' => 'rooms#index', as: 'room_index'
  post 'rooms/index' => 'rooms#index', as: 'room_index_post'
  get 'rooms/edit/:id' => 'rooms#edit', as: 'room_edit'
  patch 'rooms/update/:id' => 'rooms#update'
  get 'rooms/show/:id' => 'rooms#show', as: 'room'
  get 'room/destroy/:id', controller: 'rooms', action: 'destroy', as: 'destroy_room'
  get 'rooms/json_of_categories_by_school_room' => 'rooms#json_of_categories_by_school_room'
  post 'rooms/filter_rooms' => 'rooms#filter_rooms', as: 'rooms_filter'

  # Course
  get 'courses/courses_by_user' => 'courses#courses_by_user', as: 'courses_by_user'

  #SchoolRooms
  get 'school_rooms/index' => 'school_rooms#index', as: 'school_rooms_index'
  get 'school_rooms/new' => 'school_rooms#new', as: 'school_rooms_new'
  post 'school_rooms/create' => 'school_rooms#create'
  get 'school_rooms/edit/:id' => 'school_rooms#edit', as: 'school_rooms_edit'
  patch 'school_rooms/update/:id', controller: 'school_rooms', action: 'update', as: 'school_rooms_update'
  post 'school_rooms/search_disciplines' => 'school_rooms#search_disciplines', as: 'search_disciplines'
  get 'school_rooms/destroy/:id', controller: 'school_rooms', action: 'destroy', as: 'destroy_school_room'
  get 'school_rooms/search_courses/:code' => 'school_rooms#search_courses', as: 'search_courses'

  # Parsers
  post "/upload_buildings", controller: 'parsers', action: 'upload_buildings'
  post "/upload", controller: 'parsers', action: 'upload_rooms'
  get "/parsers", controller: 'parsers', action: 'index', as: "index_parser"
  post "/upload_department", controller: 'parsers', action: 'upload_departments'
  post "/upload_courses", controller: 'parsers', action: 'upload_courses'
  post "/upload_disciplines", controller: 'parsers', action: 'upload_disciplines'
  #resources :parsers

  # Period
  get 'periods/index' => 'periods#index' , as: 'period_index'
  get 'periods/edit/:id' => 'periods#edit', as: 'period_edit'
  post 'periods/update' => 'periods#update', as: 'period_update'

  # Reports
  get 'reports/by_room'=> 'reports#by_room', as: 'reports_by_room'
  get 'reports/generate_by_room' => 'reports#generate_by_room', as: 'generate_by_room'
  get 'reports/json_of_rooms_by_department' => 'reports#json_of_rooms_by_department'
  get 'reports/json_of_rooms_with_parts_of_name' => 'reports#json_of_rooms_with_parts_of_name'
  post 'reports/generate_by_room' => 'reports#generate_by_room'

  # Reports School Rooms
  get 'reports_school_rooms/school_room_all' => 'reports_school_rooms#report_school_room_all', as: 'reports_school_room_all'
  get 'reports_school_rooms/school_rooms_allocated' => 'reports_school_rooms#report_school_room_allocated', as: 'reports_school_room_allocated'
  get 'reports_school_rooms/school_room_not_allocated' => 'reports_school_rooms#report_school_room_not_allocated', as: 'reports_school_room_not_allocated'
  get 'reports_school_rooms/school_room' => 'reports_school_rooms#school_reports', as: 'reports_school_room'

  #Reports by building
  get 'reports/by_building'=> 'reports#by_building', as: 'reports_by_building'
  get 'reports/generate_by_building/:id' => 'reports#generate_by_building', as: 'generate_by_building'
  post 'reports/by_building' => 'reports#by_building', as: 'reports_by_building_post'

  #Reports Disciplines
  get 'reports_disciplines/generate_by_discipline/:id' => 'reports_disciplines#generate_by_discipline', as: 'generate_by_discipline'
  get 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline'
  post 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline_post'

  # Allocation
  get 'allocations/new/:school_room_id' => 'allocations#new' , as: 'allocations_new'
  post 'allocations/create' => 'allocations#create' , as: 'allocations_create'
  post 'allocations/allocation_by_solicitation' => 'allocations#allocation_by_solicitation' , as: 'allocation_by_solicitation'
  get 'allocations/destroy/:id', controller: 'allocations', action: 'destroy', as: 'allocations_destroy'
  get 'allocations/room_allocations_by_day' => 'allocations#room_allocations_by_day', as: 'room_allocations_by_day'
  get 'allocations/destroy_all_allocation_date/:id', controller: 'allocations', action: 'destroy_all_allocation_date', as: 'allocations_destroy_all_allocation_date'
  get 'allocations/destroy_all_allocations/:id' => 'allocations#destroy_all_allocations', as: 'allocations_destroy_all_allocations'

  # allocation_extension
  get 'allocation_extensions/new' => 'allocation_extensions#new' , as: 'allocation_extensions_new'
  post 'allocation_extensions/create' => 'allocation_extensions#create' , as: 'allocation_extensions_create'

  # Extension
  post 'extensions/create' => 'extensions#create' , as: 'extensions_create'

  # Solicitation
  get 'solicitations/index' => 'solicitations#index', :as => 'solicitations_index'
  get 'solicitations/show/' => 'solicitations#show', as: 'solicitations_show'
  get 'solicitations/allocation_period/:school_room_id' => 'solicitations#allocation_period', :as => 'allocation_period'
  get 'solicitations/adjustment_period/:school_room_id' => 'solicitations#adjustment_period', :as => 'adjustment_period'
  post 'solicitations/save_allocation_period' => 'solicitations#save_allocation_period', :as => 'save_allocation_period'
  post 'solicitations/save_adjustment_period' => 'solicitations#save_adjustment_period', :as => 'save_adjustment_period'
  get 'solicitations/avaliable_rooms_by_department' => 'solicitations#avaliable_rooms_by_department', :as => 'avaliable_rooms_by_department'
  get 'solicitations/recuse_solicitation' => 'solicitations#recuse_solicitation', as: 'solicitations_recuse_solicitation'
  post 'solicitations/approve_solicitation' => 'solicitations#approve_solicitation', as: 'solicitations_approve_solicitation'

  # API Users
  get 'api_users/index' => 'api_users#index', as: 'api_users_index'
  get 'api_users/new' => 'api_users#new', as: 'api_users_new'
  post 'api_users/create' => 'api_users#create', as: 'api_users_create'
  get 'api_users/edit/:id' => 'api_users#edit', as: 'api_users_edit'
  put 'api_users/update/:id' => 'api_users#update', as: 'api_users_update'
  get 'api_users/show/:id' => 'api_users#show', as: 'api_users_show'
  get 'api_users/destroy/:id' => 'api_users#destroy', as: 'api_users_destroy'

  # API
  namespace :api, default: { format: :json }, path: '/api' do
    get 'all_rooms' => 'apis#all_rooms'
    get 'building/:code' => 'apis#buildings'
    get 'school_rooms/all' => 'apis#all_school_room'
    get 'department_allocations/:code' => 'apis#department_allocations'
    get 'discipline_allocations/:code' => 'apis#discipline_allocations'
    get 'school_rooms/all_school_rooms' => 'apis#all_school_rooms', as: 'api_all_school_rooms'
    get 'school_rooms_of_room/:code' => 'apis#school_rooms_of_room'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

SIGS/app/models/school_room.rb
# frozen_string_literal: true

# Classe modelo da Turma
class SchoolRoom < ApplicationRecord
  belongs_to :discipline
  has_and_belongs_to_many :courses, class: 'Course'
  has_and_belongs_to_many :category
  has_many :allocations, dependent: :destroy
  has_one :user

  validates :name, uniqueness: {
    scope: :discipline,
    message: 'Turma com nome já cadastrado'
  }

  validates_presence_of :name, message: 'Turma não pode ser vazia'
  validates_presence_of :vacancies, message: 'Capacidade não pode ser vazia'
  validates_presence_of :discipline, message: 'Disciplina não pode ser vazia'
  validates_presence_of :courses, message: 'Turma deve haver pelo menos um curso'

  validates_numericality_of :vacancies,
                            greater_than_or_equal_to: 5,
                            message: 'A capacidade mínima é 5 vagas'
  validates_numericality_of :vacancies,
                            less_than_or_equal_to: 500,
                            message: 'A capacidade máxima é 500 vagas'

  validate :validate_courses

  def validate_courses
    response = ''
    unless courses.size.zero?
      response = courses[0].shift

      courses.each do |course_of_school_room|
        if course_of_school_room.shift != response
          errors.add(:courses, 'Cursos devem ser do mesmo período')
          break
        end
      end
    end
    response
  end
end

SIGS/app/controllers/school_rooms_controller.rb
# frozen_string_literal: true

# class that create school rooms
class SchoolRoomsController < ApplicationController
  before_action :logged_in?
  before_action :authenticate_coordinator?, except: [:index]

  def new
    @school_room = SchoolRoom.new
    @all_courses = Course.all
  end

  def create
    @school_room = SchoolRoom.new(school_rooms_params)
    @school_room.name.upcase!
    @all_courses = Course.all
    if @school_room.save
      redirect_to school_rooms_index_path, flash: { success: 'Turma criada' }
    else
      ocurred_errors(@school_room)
      render :new
    end
  end

  def edit
    @school_room = SchoolRoom.find(params[:id])
    @all_courses = Course.all
  end

  def index
    if permission[:level] == 1
      @my_school_rooms = SchoolRoom.joins(:discipline).merge(
        Discipline.order(:name).where(department_id: department_by_coordinator)
      ).order(:name)
      @disciplines = discipline_of_department(department_by_coordinator)
                     .order(:name)
                     .map(&:name)
    else
      @my_school_rooms = SchoolRoom.all
    end
  end

  def search_disciplines
    @search_attribute = params[:current_search][:search]
    @disciplines = discipline_of_department(department_by_coordinator).where(
      'name LIKE :search', search: "%#{@search_attribute}%"
    ).order(:name)
    if @disciplines.present?
      @school_rooms = school_rooms_of_disciplines(@disciplines)
    else
      flash[:notice] = 'Nenhuma turma encontrada'
      redirect_to school_rooms_index_path
    end
  end

  def search_courses
    require 'json'
    search_param = params[:code]
    courses = Course.find_by(code: search_param)
    render inline: courses.to_json
  end

  def update
    @school_room = SchoolRoom.find(params[:id])
    @all_courses = Course.all
    if @school_room.update_attributes(school_rooms_params_update)
      success_mesage = 'A turma foi alterada com sucesso'
      redirect_to school_rooms_index_path, flash: { success: success_mesage }
    else
      ocurred_errors(@school_room)
      render :edit
    end
  end

  def destroy
    @school_room = SchoolRoom.find(params[:id])
    coordinator = Coordinator.find_by(user_id: current_user.id)
    if permission[:level] == 1 &&
       coordinator.course.department == @school_room.discipline.department
      @school_room.destroy
      flash[:success] = 'A turma foi excluída com sucesso'
    else
      flash[:error] = 'Permissão negada'
    end
    redirect_to school_rooms_index_path
  end

  private

  def school_rooms_params
    params[:school_room].permit(
      :name,
      :discipline_id,
      :vacancies,
      course_ids: [],
      category_ids: []
    )
  end

  def school_rooms_params_update
    params[:school_room].permit(
      :discipline_id,
      :vacancies,
      course_ids: [],
      category_ids: []
    )
  end

  def school_rooms_of_disciplines(disciplines)
    SchoolRoom.where(discipline: disciplines).order(:name)
  end

  def department_by_coordinator
    coordinator = Coordinator.find_by(user: current_user.id)
    course = Course.find(coordinator.course_id)
    Department.find(course.department_id)
  end
end

SIGS/app/helpers/school_rooms_helper.rb
# frozen_string_literal: true

# school room module
module SchoolRoomsHelper
  def discipline_of_department(id)
    Discipline.where(department_id: id).load
  end

  def get_name(id)
    SchoolRoom.find_by(id: id).name
  end

  def get_discipline_name(id)
    SchoolRoom.find_by(id: id).discipline.name
  end

  def get_department_name(id)
    SchoolRoom.find_by(id: id).discipline.department.name
  end

  def get_vacancies(id)
    SchoolRoom.find_by(id: id).vacancies
  end

  def get_courses(id)
    SchoolRoom.find_by(id: id).courses
  end

  def get_categories(id)
    SchoolRoom.find_by(id: id).category
  end
end

SIGS/app/views/school_rooms/_show.html.erb
<table class="table">
  <tr>
    <th>Turma</th>
    <th>Disciplina</th>
    <th>Departamento</th>
    <th>Nº de Vagas</th>
    <th>Cursos</th>
    <th>Recursos</th>
  </tr>

  <tr>
    <td><%= get_name(school_room) %></td>
    <td><%= get_discipline_name(school_room) %></td>
    <td><%= get_department_name(school_room) %></td>
    <td><%= get_vacancies(school_room) %></td>
    <td>
      <% get_courses(school_room).each do |course| %>
        <%= course.name %><br>
      <% end %>
    </td>
    <td id = "school_room_ressources">
      <% line = false %>
      <% get_categories(school_room).each do |category| %>
        <% if line %>
          <br>
        <% end %>

        <%= category.name %>
        <% line = true %>
      <% end %>
    </td>
  </tr>
</table>

SIGS/app/views/school_rooms/edit.html.erb
<h2>Editar Turma</h2>
<%= form_for(@school_room, url: {action: "update"}) do |school_room| %>

  <label>Disciplina </label>
  <%= school_room.select :discipline_id, get_disciplines(current_user).collect {|d| [d.name, d.id] }%>

  <div>
    <%= school_room.label :name, "Turma" %>
    <%= school_room.text_field :name, class: 'form-control', id: 'school_room_name', :disabled => true  %>
    <%= school_room.label :vacancies, "Capacidade" %>
    <%= school_room.number_field :vacancies, class: 'form-control' %>
  </div>
  <hr>
  <div class="flexContainer search-result-block">
    <div>
      <p>Adicionar Curso</p>
      <div class="search-elements">
        <input type="text" id="input-search-courses" class="search-input" placeholder="Buscar curso por código...">
      </div>
      <div class="search-elements">
        <button type="button" id="add-course" class="icon-search-submit"> 
          <i class="fa fa-search fa-lg"></i> 
        </button>
      </div>
      <div class="" id="search-result"></div>
    </div>
    <div>
      <div class="search-elements" id="courses-list">
        <p>Cursos Adicionados</p>
        <input type="hidden" value="" name="school_room[course_ids][]" readOnly="true">
        <% @school_room.courses.each do |course| %>
          <p id="course-added-<%= course.id %>">
            <button type="button" id="button-remove" class="btn btn-default" onClick="removeCourseInList(<%= course.id %>)">
              <i class="fa fa-minus"></i>
              <%= course.name %>
            </button>
            <input type="hidden" value="<%= course.id %>" name="school_room[course_ids][]" readOnly="true">
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <br>
  <%= school_room.label :category_ids, "Categorias" %>
  <div class="checkbox-group">
    <%= school_room.collection_check_boxes(:category_ids,all_categories,:id,:name, include_blank: true)%>
  </div>
  <br>

  <%= school_room.submit "Alterar", class: 'pull-right btn btn-default btn-success' %>

<% end %>
<script type="text/javascript">
  $('#add-course').click(function(){
    searchCourses();
  });

  var course;

  function searchCourses() {
    if($('#input-search-courses').val()) {
      $.  getJSON(
        '../search_courses/' + $('#input-search-courses').val() ,{
        format: 'json'
      }).success(function(data){
        console.log(data);
        course = data;
        console.log('valor de course = ' + course);
        viewResult();
      }).error(function(){
        alert("Falha no Processamento");
      });
    }
  }

  function viewResult() {
    if(course != null) {
      $('#search-result').html(
        '<button type="button" id="button-element" class="btn btn-default" onClick="addCourseInList()"><i class="fa fa-plus"></i>' +
          course.name + '</button>');
    } else {
      $('#search-result').html(
        '<p>Nenhum curso encontrado.</p>');
    }
  }

  function addCourseInList() {
    var element = document.getElementById('course-added-' + course.id);
    if (element == null) {
      $('#courses-list').append(
        '<p id="course-added-'+course.id+'">' +
        '<button type="button" id="button-remove class="btn btn-default" onClick="removeCourseInList('+course.id+')"><i class="fa fa-minus"></i>' +
          course.name +
        '</button>' +
        '<input type="hidden" value="'+course.id+'" name="school_room[course_ids][]" readOnly="true">' + 
        '</p>');
    } else {
      var duplicate_course = document.getElementById('duplicate-course');
      if(duplicate_course == null) {
        $('#search-result').append("<p id='duplicate-course'>Este curso já pertence a esta turma.</p>");   
      }
    }
  }

  function removeCourseInList(id) {
    console.log("removendo");
    $('#course-added-'+id).remove();
    $('#search-result').html("");
  }

</script>

SIGS/app/views/school_rooms/index.html.erb
<% if permission[:level] == 1 %>
  <h1>Turmas - <%= courses_by_user.name %></h1>
<% else %>
  <h1>Turmas</h1>
<% end %>

<%= form_for(:current_search, url: search_disciplines_path) do |f|%>

  <div class="search-elements">
    <%= f.text_field :search, placeholder: "Buscar por disciplinas", id: 'input-search-field', class: 'search-input', data: {autocomplete_source: @discipline} %>
  </div>
  <div class="search-elements">
    <%= button_tag type: 'submit', class: "icon-search-submit", id: "searchButton" do %>
      <i class="fa fa-search fa-lg"></i>
    <% end %>
  </div>
  <% if permission[:level] == 1 %>
    <%= link_to "Criar Nova Turma", school_rooms_new_path, class: "btn btn-primary pull-right", role: "button" %>
  <% end %>
<% end %>


<% if @my_school_rooms.count == 0 %>
  <h3>Não há turmas cadastradas no momento.</h3>
<% else %>
  <table class="table table-hover">
    <tr>
      <th>Disciplina</th>
      <th>Turma</th>
      <th>Cursos</th>
      <th>Nº de Vagas</th>
      <% if permission[:level] == 1 %>
        <th style="text-align:center">Alocar</th>
        <th style="text-align:center">Solicitar Alocação</th>
        <th style="text-align:center">Desalocar</th>
        <th style="text-align:center">Alterar</th>
        <th style="text-align:center">Excluir</th>
      <% end %> 
    </tr>
    <% @my_school_rooms.each do |school_room| %>
      <tr>
        <td><%= school_room.discipline.name %></td>
        <td><%= school_room.name %></td>
        <td>
          <% school_room.courses.each do |course| %>
            <%= course.name %> <br>
          <% end %>
        <td><%= school_room.vacancies %></td>
        <% if permission[:level] == 1 %>  
          </td>
            <td style="text-align:center"><%= link_to image_tag("icon_alloc.png"), allocations_new_path(school_room.id) %></td>
            <td style="text-align:center"><%= link_to image_tag("icon_request_alloc.png"), allocation_period_path(school_room.id) %></td>
            <td style="text-align:center"><%= link_to image_tag("icon_alloc_red.png"), allocations_destroy_path(school_room.id) %></td>
            <td style="text-align:center"><%= link_to image_tag("icon_edit.png"), school_rooms_edit_path(school_room.id) %></td>
            <td style="text-align:center"><%= link_to image_tag("icon_trash.png"), destroy_school_room_path(school_room.id), data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"} %></td>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

SIGS/app/views/school_rooms/new.html.erb
<h2>Nova Turma</h2>

<%= form_for @school_room, url: school_rooms_create_path do |school_room| %>

  <label>Disciplina </label>
  <%= school_room.select :discipline_id, get_disciplines(current_user).collect {|d| [d.name, d.id] }%>

  <div class="short_input">
    <%= school_room.label :name, "Turma" %>
    <%= school_room.text_field :name, class: 'form-control' %>
  </div>

  <p>Capacidade</p>
  <div class="checkbox-group">
    <%= school_room.number_field :vacancies %>
  </div>
  <br>

  <hr>
  <div class="flexContainer search-result-block">
    <div>
      <p>Adicionar Curso</p>
      <div class="search-elements">
        <input type="text" id="input-search-courses" class="search-input" placeholder="Buscar curso por código...">
      </div>
      <div class="search-elements">
        <button type="button" id="add-course" class="icon-search-submit"> 
          <i class="fa fa-search fa-lg"></i> 
        </button>
      </div>
      <div class="" id="search-result"></div>
    </div>
    <div>
      <div class="search-elements" id="courses-list">
        <p>Cursos Adicionados</p>
        <input type="hidden" value="" name="school_room[course_ids][]" readOnly="true">
      </div>
    </div>
  </div>

  <hr>
  <p>Categorias</p>
  <div class="checkbox-group">
    <%= school_room.collection_check_boxes(:category_ids,all_categories,:id,:name, include_blank: true)%>
  </div>
  <br>

  <%= school_room.submit "Salvar", class: 'pull-right btn btn-default btn-success' %>

<% end %>

<script type="text/javascript">
  $('#add-course').click(function(){
    searchCourses();
  });

  var course;

  function searchCourses() {
    if($('#input-search-courses').val()) {
      $.  getJSON(
        '../school_rooms/search_courses/' + $('#input-search-courses').val() ,{
        format: 'json'
      }).success(function(data){
        console.log(data);
        course = data;
        console.log('valor de course = ' + course);
        viewResult();
      }).error(function(){
        alert("Falha no Processamento");
      });
    }
  }

  function viewResult() {
    if(course != null) {
      $('#search-result').html(
        '<button type="button" id="button-element" class="btn btn-default" onClick="addCourseInList()"><i class="fa fa-plus"></i>' +
          course.name + '</button>');
    } else {
      $('#search-result').html(
        '<p>Nenhum curso encontrado.</p>');
    }
  }

  function addCourseInList() {
    var element = document.getElementById('course-added-' + course.id);
    if (element == null) {
      $('#courses-list').append(
        '<p id="course-added-'+course.id+'">' +
        '<button type="button" id="button-remove class="btn btn-default" onClick="removeCourseInList('+course.id+')"><i class="fa fa-minus"></i>' +
          course.name +
        '</button>' +
        '<input type="hidden" value="'+course.id+'" name="school_room[course_ids][]" readOnly="true">' + 
        '</p>');
    } else {
      var duplicate_course = document.getElementById('duplicate-course');
      if(duplicate_course == null) {
        $('#search-result').append("<p id='duplicate-course'>Este curso já pertence a esta turma.</p>");   
      }
    }
  }

  function removeCourseInList(id) {
    $('#course-added-'+id).remove();
    $('#search-result').html("");
  }

</script>

SIGS/app/views/school_rooms/search_disciplines.html.erb
<h1>Pesquisa de Turmas</h1>

<%= form_for(:current_search, url: search_disciplines_path) do |f|%>

  <div class="search-elements">
    <%= f.text_field :search, placeholder: "Buscar por disciplinas", id: 'input-search-field', class: 'search-input', data: {autocomplete_source: @disciplines} %>
  </div>
  <div class="search-elements">
    <%= button_tag type: 'submit', class: "icon-search-submit", id: "searchButton" do %>
      <i class="fa fa-search fa-lg"></i>
    <% end %>
  </div>
<% end %>

<% if @disciplines.present? %>

	<i>Exibindo resultados para </i>
	<strong><%= @search_attribute %></strong>
	<table class="table table-hover">
    <tr>
      <th>Disciplina</th>
			<th>Turma</th>
      <th>Cursos</th>
      <th>Nº de Vagas</th>
      <th style="text-align:center">Alocar</th>
      <th style="text-align:center">Solicitar Alocação</th>
      <th style="text-align:center">Desalocar</th>
      <th style="text-align:center">Alterar</th>
      <th style="text-align:center">Excluir</th>
    </tr>
    <% @school_rooms.each do |school_room| %>
      <tr>
				<td><%= school_room.discipline.name %></td>
        <td><%= school_room.name %></td>
        <td>
          <% school_room.courses.each do |course| %>
            <%= course.name %> <br>
          <% end %>
        </td>
        <td><%= school_room.vacancies %></td>
        <td style="text-align:center"><%= link_to image_tag("icon_alloc.png"), allocations_new_path(school_room.id) %></td>
        <td style="text-align:center"><%= link_to image_tag("icon_request_alloc.png"), allocation_period_path(school_room.id) %></td>
        <td style="text-align:center"><%= link_to image_tag("icon_alloc_red.png"), allocations_destroy_path(school_room.id) %></td>
        <td style="text-align:center"><%= link_to image_tag("icon_edit.png"), school_rooms_edit_path(school_room.id) %></td>
				<td style="text-align:center"><%= link_to image_tag("icon_trash.png"), destroy_school_room_path(school_room.id), data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"} %></td>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>