SIGS/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  # Categories
  get 'categories/new' => 'categories#new' , as: 'categories_new'
  post 'categories/create' => 'categories#create' , as: 'categories_create'
  get 'categories/index' => 'categories#index' , as: 'categories_index'
  get 'categories/edit/:id' => 'categories#edit', as: 'categories_edit'
  patch 'categories/update/:id', controller: 'categories', action: 'update', as: 'categories_update'
  get 'categories/destroy/:id', controller: 'categories', action: 'destroy', as: 'categories_destroy'

  # Sessions
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  # User
  get 'users/index' => 'users#index', as: 'user_index'
  get 'users/new' => 'users#new' , as: 'user_new'
  post 'users/new' => 'users#create' , as:'user_create'
  get '/users/:id' => 'users#show', as: 'user'
  get 'users/edit/:id' => 'users#edit', as: 'user_edit'
  patch 'users/update/:id', controller: 'users', action: 'update', as: 'user_update'
  get 'users/destroy/:id', controller: 'users', action: 'destroy', as: 'user_destroy'

  # Coordinator

  # Department Assistant

  # Administrative Assistant
  get 'administrative_assistants/registration_request' => 'administrative_assistants#registration_request', as: 'registration_request'
  get 'administrative_assistants/enable_registration/:id' => 'administrative_assistants#enable_registration', as: 'enable_registration'
  get 'administrative_assistants/decline_registration/:id' => 'administrative_assistants#decline_registration', as: 'decline_registration'
  get 'administrative_assistants/destroy_users/:id' => 'administrative_assistants#destroy_users', as: 'destroy_users'

  # Room
  get 'rooms/index' => 'rooms#index', as: 'room_index'
  post 'rooms/index' => 'rooms#index', as: 'room_index_post'
  get 'rooms/edit/:id' => 'rooms#edit', as: 'room_edit'
  patch 'rooms/update/:id' => 'rooms#update'
  get 'rooms/show/:id' => 'rooms#show', as: 'room'
  get 'room/destroy/:id', controller: 'rooms', action: 'destroy', as: 'destroy_room'
  get 'rooms/json_of_categories_by_school_room' => 'rooms#json_of_categories_by_school_room'
  post 'rooms/filter_rooms' => 'rooms#filter_rooms', as: 'rooms_filter'

  # Course
  get 'courses/courses_by_user' => 'courses#courses_by_user', as: 'courses_by_user'

  #SchoolRooms
  get 'school_rooms/index' => 'school_rooms#index', as: 'school_rooms_index'
  get 'school_rooms/new' => 'school_rooms#new', as: 'school_rooms_new'
  post 'school_rooms/create' => 'school_rooms#create'
  get 'school_rooms/edit/:id' => 'school_rooms#edit', as: 'school_rooms_edit'
  patch 'school_rooms/update/:id', controller: 'school_rooms', action: 'update', as: 'school_rooms_update'
  post 'school_rooms/search_disciplines' => 'school_rooms#search_disciplines', as: 'search_disciplines'
  get 'school_rooms/destroy/:id', controller: 'school_rooms', action: 'destroy', as: 'destroy_school_room'
  get 'school_rooms/search_courses/:code' => 'school_rooms#search_courses', as: 'search_courses'

  # Parsers
  post "/upload_buildings", controller: 'parsers', action: 'upload_buildings'
  post "/upload", controller: 'parsers', action: 'upload_rooms'
  get "/parsers", controller: 'parsers', action: 'index', as: "index_parser"
  post "/upload_department", controller: 'parsers', action: 'upload_departments'
  post "/upload_courses", controller: 'parsers', action: 'upload_courses'
  post "/upload_disciplines", controller: 'parsers', action: 'upload_disciplines'
  #resources :parsers

  # Period
  get 'periods/index' => 'periods#index' , as: 'period_index'
  get 'periods/edit/:id' => 'periods#edit', as: 'period_edit'
  post 'periods/update' => 'periods#update', as: 'period_update'

  # Reports
  get 'reports/by_room'=> 'reports#by_room', as: 'reports_by_room'
  get 'reports/generate_by_room' => 'reports#generate_by_room', as: 'generate_by_room'
  get 'reports/json_of_rooms_by_department' => 'reports#json_of_rooms_by_department'
  get 'reports/json_of_rooms_with_parts_of_name' => 'reports#json_of_rooms_with_parts_of_name'
  post 'reports/generate_by_room' => 'reports#generate_by_room'

  # Reports School Rooms
  get 'reports_school_rooms/school_room_all' => 'reports_school_rooms#report_school_room_all', as: 'reports_school_room_all'
  get 'reports_school_rooms/school_rooms_allocated' => 'reports_school_rooms#report_school_room_allocated', as: 'reports_school_room_allocated'
  get 'reports_school_rooms/school_room_not_allocated' => 'reports_school_rooms#report_school_room_not_allocated', as: 'reports_school_room_not_allocated'
  get 'reports_school_rooms/school_room' => 'reports_school_rooms#school_reports', as: 'reports_school_room'

  #Reports by building
  get 'reports/by_building'=> 'reports#by_building', as: 'reports_by_building'
  get 'reports/generate_by_building/:id' => 'reports#generate_by_building', as: 'generate_by_building'
  post 'reports/by_building' => 'reports#by_building', as: 'reports_by_building_post'

  #Reports Disciplines
  get 'reports_disciplines/generate_by_discipline/:id' => 'reports_disciplines#generate_by_discipline', as: 'generate_by_discipline'
  get 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline'
  post 'reports_disciplines/by_discipline' => 'reports_disciplines#by_discipline', as: 'reports_by_discipline_post'

  # Allocation
  get 'allocations/new/:school_room_id' => 'allocations#new' , as: 'allocations_new'
  post 'allocations/create' => 'allocations#create' , as: 'allocations_create'
  post 'allocations/allocation_by_solicitation' => 'allocations#allocation_by_solicitation' , as: 'allocation_by_solicitation'
  get 'allocations/destroy/:id', controller: 'allocations', action: 'destroy', as: 'allocations_destroy'
  get 'allocations/room_allocations_by_day' => 'allocations#room_allocations_by_day', as: 'room_allocations_by_day'
  get 'allocations/destroy_all_allocation_date/:id', controller: 'allocations', action: 'destroy_all_allocation_date', as: 'allocations_destroy_all_allocation_date'
  get 'allocations/destroy_all_allocations/:id' => 'allocations#destroy_all_allocations', as: 'allocations_destroy_all_allocations'

  # allocation_extension
  get 'allocation_extensions/new' => 'allocation_extensions#new' , as: 'allocation_extensions_new'
  post 'allocation_extensions/create' => 'allocation_extensions#create' , as: 'allocation_extensions_create'

  # Extension
  post 'extensions/create' => 'extensions#create' , as: 'extensions_create'

  # Solicitation
  get 'solicitations/index' => 'solicitations#index', :as => 'solicitations_index'
  get 'solicitations/show/' => 'solicitations#show', as: 'solicitations_show'
  get 'solicitations/allocation_period/:school_room_id' => 'solicitations#allocation_period', :as => 'allocation_period'
  get 'solicitations/adjustment_period/:school_room_id' => 'solicitations#adjustment_period', :as => 'adjustment_period'
  post 'solicitations/save_allocation_period' => 'solicitations#save_allocation_period', :as => 'save_allocation_period'
  post 'solicitations/save_adjustment_period' => 'solicitations#save_adjustment_period', :as => 'save_adjustment_period'
  get 'solicitations/avaliable_rooms_by_department' => 'solicitations#avaliable_rooms_by_department', :as => 'avaliable_rooms_by_department'
  get 'solicitations/recuse_solicitation' => 'solicitations#recuse_solicitation', as: 'solicitations_recuse_solicitation'
  post 'solicitations/approve_solicitation' => 'solicitations#approve_solicitation', as: 'solicitations_approve_solicitation'

  # API Users
  get 'api_users/index' => 'api_users#index', as: 'api_users_index'
  get 'api_users/new' => 'api_users#new', as: 'api_users_new'
  post 'api_users/create' => 'api_users#create', as: 'api_users_create'
  get 'api_users/edit/:id' => 'api_users#edit', as: 'api_users_edit'
  put 'api_users/update/:id' => 'api_users#update', as: 'api_users_update'
  get 'api_users/show/:id' => 'api_users#show', as: 'api_users_show'
  get 'api_users/destroy/:id' => 'api_users#destroy', as: 'api_users_destroy'

  # API
  namespace :api, default: { format: :json }, path: '/api' do
    get 'all_rooms' => 'apis#all_rooms'
    get 'building/:code' => 'apis#buildings'
    get 'school_rooms/all' => 'apis#all_school_room'
    get 'department_allocations/:code' => 'apis#department_allocations'
    get 'discipline_allocations/:code' => 'apis#discipline_allocations'
    get 'school_rooms/all_school_rooms' => 'apis#all_school_rooms', as: 'api_all_school_rooms'
    get 'school_rooms_of_room/:code' => 'apis#school_rooms_of_room'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

SIGS/app/models/allocation.rb
# frozen_string_literal: true

# class that create allocations
class Allocation < ApplicationRecord
  belongs_to :room
  belongs_to :school_room
  belongs_to :user
  has_many :all_allocation_date, dependent: :destroy

  validates :school_room_id,
            presence: { message: 'Informe a Turma' }
  validates :room_id,
            presence: { message: 'Informe a Sala' }
  validates :start_time,
            presence: { message: 'Informe a hora de inicio' }
  validates :final_time,
            presence: { message: 'Informe a hora de términio' }

  validate :validate_hours

  def validate_hours
    school_allocated = 'Turma já alocada neste horário'
    errors.add(:start_time, 'Horário inválido') if invalid_shift
    error_mensager = 'Alocação com horário não vago ou capacidade da sala cheia'
    errors.add(:start_time, error_mensager) if verify_time_shock_room_day
    errors.add(:start_time, school_allocated) if verify_same_school_room_schock
  end

  def invalid_shift
    shift = school_room.courses[0].shift
    (shift == 1 && final_time.strftime('%H').to_i > 18) ||
      (shift == 2 && start_time.strftime('%H').to_i < 18)
  end

  def verify_time_shock_room_day
    allocations_room = Allocation.where(day: day, room_id: room_id)
    start = start_time.strftime('%H').to_i
    final = final_time.strftime('%H').to_i
    final = 24 if final.zero?

    allocations_room.each do |allocation|
      return true if time_in_range(allocation, start, final)
    end
    false
  end

  def verify_same_school_room_schock
    allocations_room = Allocation.where(day: day, school_room_id: school_room_id)
    start = start_time.strftime('%H').to_i
    final = final_time.strftime('%H').to_i
    final = 24 if final.zero?

    allocations_room.each do |allocation|
      return true if time_in_range(allocation, start, final)
    end
    false
  end

  def time_in_range(allocation, start, final)
    allocation_start = allocation.start_time.strftime('%H').to_i
    allocation_final = allocation.final_time.strftime('%H').to_i
    allocation_final = 24 if allocation_final.zero?
    (start >= allocation_start && start < allocation_final) ||
      (final > allocation_start && final <= allocation_final)
  end
end

SIGS/app/controllers/allocations_controller.rb
# frozen_string_literal: true

# rubocop:disable ClassLength
# class that create allocations
class AllocationsController < ApplicationController
  before_action :logged_in?
  before_action :authenticate_coordinator?

  def new
    @allocations = []
    84.times do
      @allocations << Allocation.new
    end
    @school_room = SchoolRoom.find(params[:school_room_id])
    @coordinator_rooms = current_user.coordinator.course.department.rooms
  end

  def create
    allocations_params = get_valid_allocations_params(params)
    allocations_params.each do |allocation_param|
      save_allocation(allocation_param)
    end
    school_room_id = allocations_params.first[:school_room_id]
    redirect_to allocations_new_path(school_room_id)
  end

  def destroy
    @allocation_all_date_user = []
    @school_room = SchoolRoom.find(params[:id])
    @allocation_all_user = Allocation.where(school_room_id: @school_room.id)
    @allocation_all_user.each do |allocation|
      @allocation_all_date_user += AllAllocationDate.where(allocation_id: allocation.id)
    end
  end

  def save_allocation(allocation)
    new_allocation = Allocation.new(allocations_params(allocation))
    return unless new_allocation.active
    new_allocation.user_id = current_user.id

    if new_allocation.save
      pass_to_all_allocation_dates(new_allocation)
      flash[:success] = 'Alocação feita com sucesso'
    else
      ocurred_errors(new_allocation)
    end
  end
  # rubocop:enable Metrics/MethodLength, Metrics/BlockLength, Metrics/AbcSize
  # rubocop:enable Metrics/LineLength
  # rubocop:enable Style/WordArray, Style/MultilineArrayBraceLayout

  def destroy_all_allocations
    school_room_id = SchoolRoom.find(params[:id]).id
    allocations_sh = Allocation.where(school_room_id: school_room_id)
    allocations_sh.each(&:destroy)
    flash[:success] = 'Desalocação feita com sucesso'
    redirect_to allocations_destroy_path(school_room_id)
  end

  def destroy_all_allocation_date
    @all_allocation_date_delete = AllAllocationDate.find(params[:id])
    @school_room = SchoolRoom.find_by(
      id: @all_allocation_date_delete.allocation.school_room.id
    )
    @all_allocation_date_delete.destroy
    flash[:success] = 'Desalocação feita com sucesso'
    redirect_to allocations_destroy_path(@school_room.id)
  end

  def room_allocations_by_day
    require 'json'

    data = []
    (6..23).each do |hour|
      data << make_rows(hour)
    end
    render inline: data.to_json
  end

  private

  def get_valid_allocations_params(params, group_allocation = [], valid = [])
    [:Segunda, :Terça, :Quarta, :Quinta, :Sexta, :Sábado].each do |day_of_week|
      exist = false
      ('6'..'22').to_a.each do |index|
        next if params[day_of_week][index].nil?
        if params[day_of_week][index][:active] == '1' && !exist
          group_allocation.push params[day_of_week][index]
          valid.push index
          valid.push day_of_week
          exist = true
        elsif params[day_of_week][index][:active] == '1'
          group_allocation.last[:final_time] = params[day_of_week][index][:final_time]
        else
          exist = false
        end
      end
    end
    group_allocation
  end

  def pass_to_all_allocation_dates(allocation)
    period = Period.find_by(period_type: 'Letivo')
    date = period.initial_date
    while date != period.final_date
      all_allocation_date = AllAllocationDate.new
      all_allocation_date.allocation_id = allocation.id

      %w[Segunda Terça Quarta Quinta Sexta Sabado].each_with_index do |day, index|
        next unless allocation.day == day && date.wday == index + 1
        all_allocation_date.day = date
        all_allocation_date.save
        all_allocation_date = nil
      end
      date += 1
    end
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  # rubocop:disable Metrics/LineLength
  def allocations_params(my_params)
    my_params.permit(:room_id,
                     :school_room_id,
                     :day,
                     :start_time,
                     :final_time,
                     :active)
  end

  def make_rows(hour)
    @row = [hour.to_s + ':00']
    %w[Segunda Terça Quarta Quinta Sexta Sabado].each do |day_of_week|
      allocations = Allocation.where(room_id: params[day_of_week]).where(day: day_of_week)
      allocations_start = allocations.where('DATE_FORMAT(start_time, "%H") <= ?', hour)
                                     .where('DATE_FORMAT(final_time, "%H") > ?', hour)
      make_cell(allocations_start, hour, Room.find(params[day_of_week].to_i))
    end
    @row
  end

  def make_cell(allocations_start, hour, room)
    cell = ''
    if allocations_start.size.zero?
      cell = ' '
    else
      cell = ''
      exist = false
      allocations_start.each do |allocation|
        cell += allocation.school_room.discipline.name unless exist
        cell += '<br>Turma:' +
                allocation.school_room.name
        exist = true
      end
    end
    data_allocation = []
    data_allocation.push cell
    data_allocation.push params[:school_room]
    data_allocation.push room.id
    data_allocation.push hour.to_s
    data_allocation.push((hour + 1).to_s)
    data_allocation.push SchoolRoom.find(params[:school_room]).courses.first.shift
    @row << data_allocation
  end

  # rubocop:enable Metrics/MethodLength, Metrics/BlockLength, Metrics/AbcSize
  # rubocop:enable Metrics/CyclomaticComplexity, Metrics/LineLength
end
# rubocop:enable ClassLength

SIGS/app/helpers/allocation_helper.rb
# frozen_string_literal: true

# module to allocations
module AllocationHelper
end

SIGS/app/views/allocations/create.html.erb
<h1>Allocations#create</h1>
<p>Find me in app/views/allocations/create.html.erb</p>

SIGS/app/views/allocations/destroy.html.erb
<h1>Destruir Alocação</h1>

<%= render partial: "school_rooms/show", locals: {school_room: @school_room} %>

<%= button_to 'Desalocar tudo', allocations_destroy_all_allocations_path(@school_room.id),
                                data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"},
                                method: :get, class: "btn btn-lg btn-danger"%>

<div class="deallocation-table">
  <table class="table table-hover">
    <tr>
      <th>Sala</th>
      <th>Data</th>
      <th>Dia da semana</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th style="text-align:center">Desalocar</th>
    </tr>
    <% @allocation_all_date_user.each do |allocation_date| %>
      <tr>
        <td><%= allocation_date.allocation.room.name %></td>
        <td><%= allocation_date.day%></td>
        <td><%= allocation_date.allocation.day%></td>
        <td><%= allocation_date.allocation.start_time.strftime('%H')%>H</td>
        <td><%= allocation_date.allocation.final_time.strftime('%H')%>H</td>

        <td style="text-align:center"><%= link_to 'Desalocar', allocations_destroy_all_allocation_date_path(allocation_date.id),
                                                               data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"},
                                                               class: "btn btn-default btn-danger" %></td>
        </td>
      </tr>
    <% end %>
  </table>
</div>

SIGS/app/views/allocations/edit.html.erb
<h1>Allocations#edit</h1>
<p>Find me in app/views/allocations/edit.html.erb</p>

SIGS/app/views/allocations/index.html.erb
<h1>Allocations#index</h1>
<p>Find me in app/views/allocations/index.html.erb</p>

SIGS/app/views/allocations/new.html.erb
<h1>Alocar Turma</h1>

<%= render partial: "school_rooms/show", locals: {school_room: @school_room} %>

<%= hidden_field_tag :school_room, @school_room.id %>

<%= form_tag allocations_create_path do %>

  <% days = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"] %>
  <label for="select-room">Selecionar sala: </label>
  <select id="select-room">
    <%= options_from_collection_for_select(@coordinator_rooms, :id, :name) %>
  </select>
  <table class="table table-hover time_grid">
    <tr>
      <th>Horários</th>
      <% days.each do |day| %>
        <td>
          <strong><%= day %></strong>
        </td>
      <% end %>
    </tr>
    <tr>
      <th></th>
      <% days.each do |day| %>
        <td>
          <select id="select-<%=day%>" class="autofill-field selectAlocar">
            <%= options_from_collection_for_select(@coordinator_rooms, :id, :name) %>
          </select>
        </td>
      <% end %>
    </tr>
  </table>
  <table class="table table-hover time_grid" id="hours_table">
  </table>
  <%= submit_tag "Salvar", class: 'pull-right btn btn-default btn-success' %>
<% end %>

<script>

  $(document).ready(function(){
    ajaxReloadTable();
  });

  $(".autofill-field").change(function() {
    ajaxReloadTable();
  });

  $("#select-room").change(function() {
    if ($("#select-Segunda").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Segunda").val($("#select-room").val());}
    if ($("#select-Terça").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Terça").val($("#select-room").val());}
    if ($("#select-Quarta").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Quarta").val($("#select-room").val());}
    if ($("#select-Quinta").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Quinta").val($("#select-room").val());}
    if ($("#select-Sexta").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Sexta").val($("#select-room").val());}
    if ($("#select-Sábado").hasClass("not-modify")) {}// Nothing do
    else {$("#select-Sábado").val($("#select-room").val());}
    ajaxReloadTable();
  });

  function ajaxReloadTable() {
    $.getJSON('../room_allocations_by_day?Segunda=' + $("#select-Segunda").val() +
    '&Terça=' + $("#select-Terça").val()  +
    '&Quarta=' + $("#select-Quarta").val() +
    '&Quinta=' + $("#select-Quinta").val() +
    '&Sexta=' + $("#select-Sexta").val() +
    '&Sabado=' + $("#select-Sábado").val() +
    '&school_room=' + $("#school_room").val(), {
      format: 'json'
    }).success(function(data){
      generateTable(data);
    }).error(function(){
      alert("Falha no Processamento");
    });
  }

  function generateTable(data) {
    var school_room = $("#school_room").val();
    var string = "";
    var day = ["", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];
    var shift = data[0][1][5];
    var disabled;
    for(row = 0; row < 17; row++) {
      if((row <= 11 && shift == 1) || (row > 11 && shift == 2))
        disabled = false;
      else {
        disabled = true;
      }
      string += "<tr>"
      for(col = 0; col < 7; col++){
        if (col == 0){
          string += "<th>" + data[row][col] + "</th>";
        } else if (data[row][col][0] == " ") {
          string += '<td id="check_' + day[col] + "_" + (row + 6) + '">';
          if(disabled) {
            string += '<input type="checkbox" value="1" name="' + day[col] + '[' + (6 + row) + '][active]" disabled/>';
          } else {
            string += '<input type="checkbox" value="1" name="' + day[col] + '[' + (6 + row) + '][active]"/>';
          }
          string += '<input value="' + data[row][col][2] + '" type="hidden" name="' + day[col] + '[' + (6 + row) +'][room_id]" />' +
          '<input value="' + data[row][col][1] + '" type="hidden" name="' + day[col] + '[' + (6 + row) +'][school_room_id]" />' +
          '<input value="' + day[col] + '" type="hidden" name="' + day[col] + '[' + (6 + row) +'][day]" />' +
          '<input value="' + data[row][col][3] + '" type="hidden" name="' + day[col] + '[' + (6 + row) +'][start_time]" />' +
          '<input value="' + data[row][col][4] + '" type="hidden" name="' + day[col] + '[' + (6 + row) +'][final_time]" />' +
        '</td>';
        } else {
          string += "<td>" + data[row][col][0] + "</td>";
        }
      }
      string += "</tr>";
    }

    $("#hours_table").html(string);
  }
</script>

SIGS/app/views/allocations/new_education.html.erb
<style type="text/css">
  table tr td{
    text-align: center;
  }
</style>

<h1>Alocação Turma</h1>

<label> Turma </label> <%= link_to "+ Criar uma nova turma" , school_rooms_new_path %><br>
<select name='school_room_id' id="school_room_id">
  <% @school_rooms_coordinator.each do |school| %>
    <option value="<%= school.id %>"><%= school.name %></option>
  <% end %>
</select>

<% days = ["Segunda","Terça","Quarta","Quinta","Sexta","Sabado"] %>
<table style="width: 100%">
<% days.each_with_index do |day, index| %>
  <tr>
    <td style="text-align: left;">
      <input type="checkbox" value="<%=index%>" id="<%= day%>_days"> <%= day%>
    </td>
    <td>
      <label>Sala:</label>
      <select name='allocation_room_id' id='room_<%= index%>'>
        <% @coordinator_rooms.each do |room| %>
          <option value="<%= room.id %>"><%= room.name %></option>
        <% end %>
      </select>
    </td>

    <td><label for="allocation_start_time">Horário Inicial:</label>
      <input type="time" name="allocation_start_time" id="start_time_<%= index%>" /></td>

    <td><label for="allocation_start_time">Horário Final:</label>
      <input type="time" name="allocation_start_time" id="final_time_<%= index%>" /></td>

    <td>
      <input type="button" name="save_<%= index%>" value="Salvar" class="pull-right btn btn-default btn-success" disabled>
    </td>
</tr>
<% end %>
</table>

<script type="text/javascript">
    $('input:checkbox').click(function(){
      $("input[name='save_" + $(this).prop("value") +"'").prop('disabled', !$(this).prop('checked'));
    });

    $('input:button').click(function(){
      $day = $(this).prop("name").split('_')[1];
      $room_id = document.getElementById('room_'+ $day).value;
      $start_time = document.getElementById('start_time_'+ $day).value;
      $final_time = document.getElementById('final_time_'+ $day).value;
      $school_room_id = document.getElementById('school_room_id').value;

      $.ajax({
        url: 'create_education?allocation[room_id]=' + $room_id + 
                    '&allocation[start_time]=' + $start_time +
                    '&allocation[final_time]=' + $final_time +
                    '&school_room_id=' + $school_room_id +
                    '&day=' + $day ,
        success: function(data){
          $('.alertContainer').html(data)
        }
      });
    });
</script>

SIGS/app/views/allocations/show.html.erb
<h1>Allocations#show</h1>
<p>Find me in app/views/allocations/show.html.erb</p>

SIGS/app/views/allocations/update.html.erb
<h1>Allocations#update</h1>
<p>Find me in app/views/allocations/update.html.erb</p>